---
dynamic:
  variables: [ $arch-debian, $device, $node-version, $distro ]
  ref: $device/$distro/$node-version/$original_ref
  skip_ext: true
---
# AUTOGENERATED FILE
FROM resin/{{ $device.id }}-buildpack-deps:latest

ENV NODE_VERSION {{ $node-version.version }}

RUN curl -SLO "{{ $node-version.url.{{ $arch-debian.id }} }}" \
	&& echo "{{ $node-version.hash.{{ $arch-debian.id }} }}" | sha256sum -c - \
	&& tar -xzf "node-v{{ $node-version.version }}-linux-{{ $arch-debian.id }}.tar.gz" -C /usr/local --strip-components=1 \
	&& rm "node-v{{ $node-version.version }}-linux-{{ $arch-debian.id }}.tar.gz" \
	&& npm config set unsafe-perm true -g --unsafe-perm \
	&& rm -rf /tmp/*

CMD ["echo","'No CMD command was set in Dockerfile! Details about CMD command could be found in Dockerfile Guide section in our Docs. Here's the link: http://docs.resin.io/#/pages/using/dockerfile.md"]
